
# ############################################### text-to-audio inference ################################################
# infer_mode : tta
# audio_pretrained_model_name_or_path: ./assets/stable-audio-open-1.0  # Required: Path to pretrained model or model identifier  Wan2.1-T2V-1.3B-Diffusers
# audio_transformer_safetensors_path: /home/chengxin/chengxin/vagen/log/sd_tta_ft_16/checkpoints/checkpoint_13/model.safetensors

# tta_infer_config: 
#   seed: 42
#   a_negative_prompt : ""
#   a_duration: 10
#   a_guidance_scale: 7    
#   a_num_inference_steps: 40 
#   a_num_waveforms_per_prompt: 1


# tta_data_info:
#   output_dir: ${output_dir}
#   prompt_index_file: /home/chengxin/chengxin/vagen/data/tta/test_avsync.json
#   sr: 44100
#   channels: 2
# ############################################### text-to-audio inference ################################################





# ################################################ text-to-video inference ################################################
# infer_mode : ttv
# video_pretrained_model_name_or_path: ./assets/Wan2.1-T2V-1.3B-Diffusers  # Required: Path to pretrained model or model identifier  Wan2.1-T2V-1.3B-Diffusers
# video_transformer_safetensors_path: null

# ttv_infer_config: 
#   seed: 42
#   v_negative_prompt : Bright tones, overexposed, static, blurred details, subtitles, style, works, paintings, images, static, overall gray, worst quality, low quality, JPEG compression residue, ugly, incomplete, extra fingers, poorly drawn hands, poorly drawn faces, deformed, disfigured, misshapen limbs, fused fingers, still picture, messy background, three legs, many people in the background, walking backwards
#   v_num_frames: 81
#   v_height: 480
#   v_width: 832
#   v_guidance_scale: 5
#   v_num_inference_steps: 40
#   v_num_videos_per_prompt: 1

# ttv_data_info:
#   output_dir: ${output_dir}
#   prompt_index_file: /home/chengxin/chengxin/vagen/data/tta/test_avsync.json
#   fps: 16
# ################################################ text-to-video inference ################################################




output_dir  : ./log/wan_sd_ttva_55_bi_infer
logging_subdir: logging


# Scheduler setting 
scheduler:
  flow_shift: 8.0
  num_train_timesteps: 1000




################################################ text-to-video-audio inference ################################################
infer_mode : ttva
jointdit_safetensor_path: /home/chengxin/chengxin/vagen/log/wan_sd_ttva_55_bi/checkpoints/checkpoint_0/model.safetensors
audio_pretrained_model_name_or_path: ./assets/stable-audio-open-1.0  # Required: Path to pretrained model or model identifier  Wan2.1-T2V-1.3B-Diffusers
audio_transformer_safetensors_path: null
video_pretrained_model_name_or_path: ./assets/Wan2.1-T2V-1.3B-Diffusers  # Required: Path to pretrained model or model identifier  Wan2.1-T2V-1.3B-Diffusers
video_transformer_safetensors_path: null
bridge_config:
  dual_dit_configs:
      num_dual_dit_blocks: 4
      num_input_channels_1: 1536
      num_input_channels_2: 1536
      num_qk_channels: 1536
      num_v_channels: 1536
      num_heads: 12
      t_emb_dim_1: 1536
      t_emb_dim_2: 1536
      video_bridge_points: [3, 7, 11, 15]
      audio_bridge_points: [2, 5, 8, 11]
      fusion_type: bicross
bridge_safetensors_path: null


ttav_infer_config: 
  seed: 42
  num_va_per_prompt: 1
  num_inference_steps: 40

                         ####
  v_negative_prompt : Bright tones, overexposed, static, blurred details, subtitles, style, works, paintings, images, static, overall gray, worst quality, low quality, JPEG compression residue, ugly, incomplete, extra fingers, poorly drawn hands, poorly drawn faces, deformed, disfigured, misshapen limbs, fused fingers, still picture, messy background, three legs, many people in the background, walking backwards
  v_num_frames: 81
  v_height: 480
  v_width: 832
  v_guidance_scale: 6    ####

  a_negative_prompt : ""
  a_duration: 5.1        ####
  a_guidance_scale: 6    ####

  

data_info:
  output_dir: ${output_dir}
  prompt_index_file: /home/chengxin/chengxin/vagen/data/tta/test_avsync.json
  video_info:
    fps: 16
  audio_info:
    sr: 44100
    channels: 2
################################################ text-to-video-audio inference ################################################
