tag: "t2a_wan_tuning_hy1kw_wonorm"     #  wan_on_audio-beta 

# For hf setting
push_to_hub   : false
hub_token     : null
hub_model_id  : null
# For logging setting
tracker_name  : null
output_dir  : ./log/wan_ttv
report_to   : wandb   # Options: ["wandb", "null"]
logging_subdir: logging
ckpt_subdir   : ckpt
wandb_subdir  : wandb
wandb_init_args:
  mode      : "offline" # online / offline
  project : "Veo3"
  name      : "ttv"
  tags      : null
  notes     : ""



# Model setting 
# From hf models and modification
pretrained_model_name_or_path: ./assets/Wan2.1-T2V-1.3B-Diffusers  # Required: Path to pretrained model or model identifier  Wan2.1-T2V-1.3B-Diffusers
                              # /apdcephfs_gy2/share_302507476/syvenwang/data/ckpt/sda/stable-audio-open-1.0/  # Required: Path to pretrained model or model identifier
revision  : null
variant   : null  # e.g., fp16
# # cache_dir: ./cache
# # Lora setting
# rank: 128  
# lora_alpha: 64



# Training parameters
resume_from_checkpoint  : null
# Seed and precision
seed            : 42
mixed_precision : null  # Options: ["no", "fp16", "bf16"]
allow_tf32      : false 
# Steps and saving
num_train_epochs        : 50
max_train_steps         : null
checkpointing_steps     : 5000
checkpoints_total_limit : null 
# For batch and LR setting
num_workers             : 20
train_batch_size_local  : 2
gradient_accumulation_steps : 1
learning_rate   : 5e-5
scale_lr        : false
lr_scheduler    : "cosine_with_restarts"  # Options: ["linear", "cosine", "cosine_with_restarts", "polynomial", "constant", "constant_with_warmup"]
lr_warmup_steps : 1000
lr_num_cycles   : 1
lr_power        : 1.0
# For optimizing training
enable_slicing  : false #
enable_tiling   : false #
gradient_checkpointing  : true
find_unused_parameters  : true #



# Optimizer
optimizer       : "adam"  # Options: ["adam", "adamw", "prodigy"]
use_8bit_adam   : false    #
adam_beta1      : 0.9
adam_beta2      : 0.95
prodigy_beta3     : null   #
prodigy_decouple  : false  #
adam_weight_decay : 0.0001
adam_epsilon      : 0.00000001
max_grad_norm     : 1.0    # [1.0, 0.5] 
prodigy_use_bias_correction : false  #
prodigy_safeguard_warmup    : false  #



# Dataset information
# Video processing



hy_dataloader:
  video_index_file: "/home/chengxin/chengxin/vagen/data/avsync/avsync-test-72B-captions.json"
  # dataset setting
  load_mode: "video_latent"
  uncond_prob: 0.1
  # DataLoader parameters
  shuffle: true
  batch_size: ${train_batch_size_local}
  num_workers: ${num_workers}
  prefetch_factor: 2    # 默认值，如果 num_workers > 0




# Validation
validation: 
  flow_shift: 5.0
  eval_steps: 100
  seed: ${seed}
  save_dir : /home/chengxin/chengxin/vagen/log
  prompt: "Two anthropomorphic cats in comfy boxing gear and bright gloves fight intensely on a spotlighted stage.:::spiderman swinging over buildings:::A panda, dressed in a small, red jacket and a tiny hat, sits on a wooden stool in a serene bamboo forest. The panda's fluffy paws strum a miniature acoustic guitar, producing soft, melodic tunes. Nearby, a few other pandas gather, watching curiously and some clapping in rhythm. Sunlight filters through the tall bamboo, casting a gentle glow on the scene. The panda's face is expressive, showing concentration and joy as it plays. The background includes a small, flowing stream and vibrant green foliage, enhancing the peaceful and magical atmosphere of this unique musical performance"
  # prompt: "A panda, dressed in a small, red jacket and a tiny hat, sits on a wooden stool in a serene bamboo forest. The panda's fluffy paws strum a miniature acoustic guitar, producing soft, melodic tunes. Nearby, a few other pandas gather, watching curiously and some clapping in rhythm. Sunlight filters through the tall bamboo, casting a gentle glow on the scene. The panda's face is expressive, showing concentration and joy as it plays. The background includes a small, flowing stream and vibrant gr1een foliage, enhancing the peaceful and magical atmosphere of this unique musical performance"
  prompt_separator: ":::"
  negetive_prompt : Bright tones, overexposed, static, blurred details, subtitles, style, works, paintings, images, static, overall gray, worst quality, low quality, JPEG compression residue, ugly, incomplete, extra fingers, poorly drawn hands, poorly drawn faces, deformed, disfigured, misshapen limbs, fused fingers, still picture, messy background, three legs, many people in the background, walking backwards
  negetive_prompt_embed : /home/chengxin/chengxin/vagen/data/negative_prompt_embed.pt
  num_videos: 1
  height: 480
  width: 832
  num_frames: 81
  guidance_scale: 5.0
  num_videos_per_prompt: 1
  num_inference_steps: 40 # 50 is default in diffusers-Wan2.1-T2V-1.3B.
  # num_inference_steps: 2
  fps: 16

